### ISSUE TITLE
Installing as per README leads to internal server error

### ISSUE THREAD

**Issue by kdambekalns** [sandstorm/Sandstorm.CookiePunch#18]
Following the README this is what I get after step 1:

`Argument 1 passed to Sandstorm\CookiePunch\Eel\Helper\CookiePunchConfig_Original::filterServicesArrayByWhenCondition() must be of the type array, null given`

The shipped settings lack an empty array as default:

```yaml
Sandstorm:
  CookiePunch:
    consent:
      services: []
```
