### ISSUE TITLE
Rich Snippets get killed

### ISSUE THREAD

**Issue by mgrundkoetter** [sandstorm/Sandstorm.CookiePunch#2]
The package also kills every rich snippet on the website. For instance things like:

```html
<script type="application/ld+json">{"@context":"http:\/\/schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/xyz.local\/"},{"@type":"ListItem","position":2,"name":"\u00dcber uns","item":"https:\/\/xyz.local\/de\/ueber-uns"}]}</script>
```

will become:

```html
<script data-type="application/ld+json" type="text/plain" data-name="default">{"@context":"http:\/\/schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https:\/\/xyz.local\/"},{"@type":"ListItem","position":2,"name":"\u00dcber uns","item":"https:\/\/xyz.local\/de\/ueber-uns"}]}</script>
```

Which makes it unusable.

**Comment by fheinze** [comment]
Thanks for your feedback.
Looks like you are the first one ;)

Yes the package kills EVERY script tag, also the inlined ones. This is intentional as these snippets might also set cookies directly. They can also add iframes or load third party JavaScript. 

CookiePunch does not know which script tags might or might not be "harmful".

**There are two ways to help with your issue:**

**_You can mark all of your tags to never be blocked_**. See [STEP 3: Never block your own javascript](https://github.com/sandstorm/Sandstorm.CookiePunch#step-3-never-block-your-own-javascript)

**_You can switch the general mode of CookiePunch so it blocks nothing on default_** and explicitly target scripts you want to be blocked.

```yaml
Sandstorm:
	CookiePunch:
  		elements:
  			# This will disable automatic blocking of every element.
  			# You will have to define patterns to block elements explicitly.
  			# By doing so you have a higher risk of things slipping through.
  			block: false
	  		patterns:
	  			"https://www.youtube.com/embed/":
	          type: iframe
	          block: true
	          group: media
```

For the next release I will try to improve docs and examples ;)

Cheers
