### ISSUE TITLE
Script is never unblocked

### ISSUE THREAD

**Issue by mgrundkoetter** [sandstorm/Sandstorm.CookiePunch#3]
We use the NEOS package "WebExcess.OpenStreetMap" on the website (just an example). Integration as in their readme.
Now we added the CookiePunch (also as in readme) and use this config:

```yaml
Sandstorm:
  CookiePunch:
    consent:
      privacyPolicyUrl: "/de/meta/datenschutz"
      storageMethod: cookie
      cookieName: cookie_punch
      cookieExpiresAfterDays: 30
      mustConsent: true
      acceptAll: true
      hideDeclineAll: false
      default: false
    purposes:
      mediaembeds: "Einbindung von externen Medien"
    groups:
      default:
        title: "notwendige Cookies"
        description: "Speichert Ihre Cookie-Auswahl, sowie weitere technisch notwendige Einstellungen."
        consent:
          required: true
      media:
        title: "externen Medien"
        purposes:
          - mediaembeds
        description: "Videos von YouTube oder Vimeo, Kartendaten von OpenStreetMaps."
        consent:
          default: false
    elements:
      patterns:
        "Packages/Neos.Neos":
          type: script
          block: false
          group: default
        "Packages/Networkteam.Neos.MailObfuscator":
          type: script
          block: false
          group: default
        "https://www.youtube.com/embed/":
          type: iframe
          block: true
          group: media
        "Packages/WebExcess.OpenStreetMap":
          type: script
          block: true
          group: media
        "openstreetmap.org":
          type: script
          block: true
          group: media
```

The cookie banner is shown as expected, everything looks fine. All the "default" scripts also appear as normal in the html source code. The problem is, that even after activating the "media" group (with or without reloading the page), the Main.js file still remains blocked:

```html
<script data-src="https://xyz.local/_Resources/Static/Packages/WebExcess.OpenStreetMap/Assets/Main.js" data-name="media">
```

Am I missing something in the configuration? I can't get the "unblock" step to work :-( What am I doing wrong?
